version: '3.7'

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    env_file:
      - ./env.prod

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - server
    volumes:
      - static_volume:/home/app/server/static

  server:
    build:
     context: .
     dockerfile: Dockerfile.prod
    command: sh -c "gunicorn server.wsgi:application --bind 0.0.0.0:8080"
    container_name: server
    depends_on:
      - postgres
    expose:
      - 8080
    hostname: server
    image: server-image
    env_file:
      - ./env.prod
    restart: always
    volumes:
      - static_volume:/home/app/server/static
    environment:
      - DEBUG=0

  redis:
    hostname: redis
    restart: always
    ports:
      - "6379"
    image: redis:6.2.1-alpine
    volumes:
      - redisdata:/data
    command: [sh, -c, "redis-server"]

volumes:
  postgresql-data:
  redisdata:
  static_volume: