version: '3.7'

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    env_file:
      - ./env.dev

  server:
    build: .
    command: sh -c "python manage.py initadmin && python manage.py runserver 0.0.0.0:8080"
    container_name: server
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    hostname: server
    image: server-image
    env_file:
      - ./env.dev
    restart: always

  redis:
    hostname: redis
    restart: always
    image: redis:6.2.1-alpine
    volumes:
      - redisdata:/data
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]

volumes:
  postgresql-data:
  redisdata:

