version: '3.7'

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  server:
    build: .
    command: sh -c "python manage.py initadmin && python manage.py runserver 0.0.0.0:8080"
    container_name: server
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    hostname: server
    image: server-image
    restart: on-failure
    env_file:
      - ./.env.dev
    restart: always

volumes:
  postgresql-data:

